---
title: 'DataCamp Assignment: R Basics'
author: "Keith Allison"
date: "9/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- "Keith"
b1 <- 45.6
b2 <- "45.6"
c1 <- seq(from = 0, to = 3)
```

**Q1**
```{r}
class(a)
```
**Q2**
```{r}
class(b1)
```
**Q3**
```{r}
class(b2)
```
**Q4**
The code gives an error because you can't add a character to a numeric object.


**Q5**
```{r}
class(b1) == class(c1)
```
**Q6**
```{r}
b1 + c1
```
This adds the value for b1 to each of the elements of c1 because b1 is numeric and c1 is a vector.

**Q7**
```{r}
v1 <- seq(from = -2, to = 2)
v1
```

**Q8**
```{r}
v2 <- v1 * 3
v2
```

**Q9**
```{r}
sum(v2)
```
**Q10**
```{r}
vec_4 <- seq(from = 1, to = 12)
mat_1 <- matrix(vec_4, nrow = 3, ncol = 4, byrow = T)
mat_1
```
**Q11**
```{r}
mat_2 <- matrix(vec_4, nrow = 3, ncol = 4, byrow = F)
mat_2
```
**Q12**
```{r}
my_list_1 <- list(5.2, "five point two", seq(from = 0, to = 5))
names(my_list_1) <- c("two", "one", "three")
my_list_1
```
**Q13**
```{r}
my_list_1[3]
```

**Q14**
```{r}
my_list_1["one"]
```
**Q15**
```{r}
my_vec = rep(1:3, 5)
my_vec
my_bool_vec <- my_vec == 3
data.frame(my_vec, my_bool_vec)
```
**Q16**
```{r}
my_vec[my_bool_vec]
```

